import { expect, test, type Page } from '@playwright/test';
import { MAP_HEIGHT, MAP_WIDTH, regionColour, seedLargeScene, TOKEN_COUNT } from '../../fixtures/large-scene.js';
import { selectScene } from '../canvas-view.js';
import { openWorkspace, seedCampaign } from '../dm.js';
import { deleteAssets, deleteCampaign, liveBar, player, tvCanvas, tvTokens, unique } from './support.js';

// The large-scene fixture (specs/10-testing-acceptance.md §3, Q-060, Q-088, D-036), generated by
// e2e/fixtures/large-scene.ts, activated from the DM view: the TV draws the 10,000 × 7,000 px map from its
// display version and all 50 tokens, each from its own image, then the map-less scene. It runs in every
// browser of the matrix, as the player view is accepted on each (specs/10-testing-acceptance.md §4).

/** The colour a layer of the player canvas drew at screen point (x, y): 0 the map, 2 the tokens. */
async function pixel(page: Page, layer: number, x: number, y: number): Promise<number[]> {
  return tvCanvas(page).evaluate(
    (element, { layer, x, y }) => {
      const target = element.querySelectorAll('canvas')[layer]!;
      const ratio = window.devicePixelRatio;
      return [...target.getContext('2d')!.getImageData(Math.round(x * ratio), Math.round(y * ratio), 1, 1).data];
    },
    { layer, x, y },
  );
}

const near = (actual: number[], expected: number[], tolerance: number) =>
  expected.every((value, index) => Math.abs(actual[index]! - value) <= tolerance);

test('the large-scene fixture goes live: the TV draws its 10,000 × 7,000 px map and 50 tokens, then the map-less scene', async ({
  browser,
}, info) => {
  test.setTimeout(180_000);
  const dmContext = await browser.newContext();
  const tvContext = await browser.newContext();
  const dm = await dmContext.newPage();
  const tv = await tvContext.newPage();
  await openWorkspace(dm);
  const tag = unique(info, 'fixture');
  const names = { campaign: `Stress campaign ${tag}`, session: 'Stress night' };
  const campaignId = await seedCampaign(dm, names.campaign, [names.session]);
  const [session] = (await (await dm.request.get(`/api/campaigns/${campaignId}/sessions`)).json()) as { id: string }[];
  const fixture = await seedLargeScene(dm.request, session!.id, tag);
  const image = (await (await dm.request.get(`/api/images/${fixture.mapImageId}`)).json()) as {
    width: number;
    height: number;
    variants: { display?: { width: number; height: number } };
  };
  expect([image.width, image.height]).toEqual([MAP_WIDTH, MAP_HEIGHT]);
  await dm.reload();

  const fetched = new Map<string, number>();
  tv.on('response', (response) => {
    const url = new URL(response.url());
    if (url.pathname.startsWith('/images/')) fetched.set(url.pathname, response.status());
  });

  try {
    await tv.goto('/');
    await selectScene(dm, { ...names, scene: `Large scene ${tag}` });
    await liveBar(dm)
      .getByRole('button', { name: `Go live: Large scene ${tag}` })
      .click();
    await expect(player(tv)).toHaveAttribute('data-scene', 'live');
    await expect.poll(async () => (await tvTokens(tv)).length, { timeout: 60_000 }).toBe(TOKEN_COUNT);

    // The TV fetched the map's display version, never the original, and each token asset's image.
    await expect.poll(() => fetched.get(`/images/${fixture.mapImageId}/display`), { timeout: 60_000 }).toBe(200);
    expect(fetched.has(`/images/${fixture.mapImageId}/original`)).toBe(false);
    for (const asset of fixture.assets) {
      await expect.poll(() => fetched.get(`/images/${asset.image_id}/display`), { timeout: 30_000 }).toBe(200);
    }
    expect(Math.max(image.variants.display!.width, image.variants.display!.height)).toBeLessThan(MAP_WIDTH);

    // The map is drawn: the middle of a square in each of four regions has that region's colour.
    const toDisplay = image.variants.display!.width / MAP_WIDTH;
    // Read with each sample: the camera settles once the TV has measured its screen.
    const camera = () =>
      tvCanvas(tv).evaluate((element: HTMLElement) => ({
        x: Number(element.dataset.cameraX),
        y: Number(element.dataset.cameraY),
        scale: Number(element.dataset.cameraScale),
      }));
    for (const [bx, by] of [
      [0, 0],
      [3, 2],
      [7, 4],
      [9, 6],
    ] as const) {
      // The canvas's world is the display version's pixels.
      const [wx, wy] = [(bx * 1000 + 550) * toDisplay, (by * 1000 + 550) * toDisplay];
      await expect
        .poll(
          async () => {
            const at = await camera();
            return near(await pixel(tv, 0, at.x + wx * at.scale, at.y + wy * at.scale), regionColour(bx, by), 40);
          },
          {
            timeout: 30_000,
            message: `region ${bx}, ${by}`,
          },
        )
        .toBe(true);
    }

    // And every token is drawn from its image: the centre of each has its asset's colour.
    const colourOf = new Map(fixture.assets.map((asset) => [asset.id, asset.colour]));
    const assetOf = new Map(fixture.tokens.map((token) => [token.id, token.asset_id]));
    type Box = { id: string; left: number; top: number; side: number };
    const boxes = async () => (await tvTokens(tv)) as unknown as Box[];
    expect(new Set((await boxes()).map((each) => each.id))).toEqual(new Set(fixture.tokens.map((token) => token.id)));
    for (const { id } of fixture.tokens) {
      const colour = colourOf.get(assetOf.get(id)!)!;
      await expect
        .poll(
          async () => {
            const token = (await boxes()).find((each) => each.id === id)!;
            return near(await pixel(tv, 2, token.left + token.side / 2, token.top + token.side / 2), colour, 40);
          },
          {
            timeout: 30_000,
            message: `token ${id}`,
          },
        )
        .toBe(true);
    }

    // The map-less scene goes live: its default extent, no tokens.
    await dm
      .getByRole('navigation', { name: 'Campaigns, sessions and scenes' })
      .getByRole('button', { name: `Map-less scene ${tag}`, exact: true })
      .click();
    await liveBar(dm)
      .getByRole('button', { name: `Go live: Map-less scene ${tag}` })
      .click();
    await expect(liveBar(dm).getByRole('status')).toHaveText(`Live: Map-less scene ${tag}`);
    await expect.poll(async () => (await tvTokens(tv)).length).toBe(0);
    await expect(player(tv)).toHaveAttribute('data-scene', 'live');
  } finally {
    await liveBar(dm)
      .getByRole('button', { name: 'Blank TV' })
      .click()
      .catch(() => undefined);
    await deleteCampaign(dm, campaignId);
    await deleteAssets(
      dm,
      fixture.assets.map((asset) => asset.id),
    );
    await dmContext.close();
    await tvContext.close();
  }
});
