-- SRV-01: the eight entities of specs/03-domain-model.md §1 (D-075).
--
-- Every table is STRICT, so a column holds only its declared type (a token's `x`
-- is never text), and WITHOUT ROWID, so no implicit sequential key exists
-- (specs/14-agent-playbook.md §8). Keys are lowercase UUIDs generated by the
-- server, except Image, keyed by the lowercase hex sha256 of its original
-- (specs/03-domain-model.md §3). The fields prepared for later phases
-- (specs/03-domain-model.md §8) are held to their MVP values by triggers, not
-- CHECK constraints, so that the phase that frees them drops a trigger instead
-- of rebuilding a table. A REAL column refuses infinity, which JSON cannot
-- carry: `abs(v) < 9e999` compares against infinity.

-- Image: identified by content; `variants` is written by the upload pipeline
-- (SRV-04). The grid preset has the shape of a scene's grid and is either wholly
-- absent or wholly present (specs/03-domain-model.md §5).
CREATE TABLE image (
  id TEXT NOT NULL PRIMARY KEY CHECK (length(id) = 64 AND id NOT GLOB '*[^0-9a-f]*'),
  mime TEXT NOT NULL CHECK (mime IN ('image/png', 'image/jpeg', 'image/webp')),
  width INTEGER NOT NULL CHECK (width > 0),
  height INTEGER NOT NULL CHECK (height > 0),
  variants TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(variants) AND json_type(variants) = 'object'),
  grid_preset_type TEXT,
  grid_preset_size REAL CHECK (abs(grid_preset_size) < 9e999),
  grid_preset_offset_x REAL CHECK (abs(grid_preset_offset_x) < 9e999),
  grid_preset_offset_y REAL CHECK (abs(grid_preset_offset_y) < 9e999),
  grid_preset_visible INTEGER,
  grid_preset_feet_per_square REAL CHECK (abs(grid_preset_feet_per_square) < 9e999),
  grid_preset_columns INTEGER,
  grid_preset_rows INTEGER,
  -- coalesce: a CHECK whose expression is NULL passes, so a NULL in the second
  -- branch must count as a refusal.
  CHECK (coalesce(
    (grid_preset_type IS NULL AND grid_preset_size IS NULL AND grid_preset_offset_x IS NULL
      AND grid_preset_offset_y IS NULL AND grid_preset_visible IS NULL
      AND grid_preset_feet_per_square IS NULL AND grid_preset_columns IS NULL AND grid_preset_rows IS NULL)
    OR (grid_preset_type IS NOT NULL AND grid_preset_size > 0 AND grid_preset_offset_x IS NOT NULL
      AND grid_preset_offset_y IS NOT NULL AND grid_preset_visible IN (0, 1)
      AND grid_preset_feet_per_square > 0 AND grid_preset_columns > 0 AND grid_preset_rows > 0),
    0
  ))
) STRICT, WITHOUT ROWID;

-- Asset: the shared library template (specs/05-assets-and-images.md §1, §2, §4).
-- `default_hidden` has no default: its starting value depends on the category (D-020).
CREATE TABLE asset (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  name TEXT NOT NULL CHECK (name <> ''),
  category TEXT NOT NULL CHECK (category IN ('pc', 'npc', 'monster', 'object')),
  image_id TEXT NOT NULL REFERENCES image (id) ON DELETE RESTRICT,
  size TEXT NOT NULL CHECK (size IN ('tiny', 'small', 'medium', 'large', 'huge', 'gargantuan')),
  default_hidden INTEGER NOT NULL CHECK (default_hidden IN (0, 1)),
  notes TEXT NOT NULL DEFAULT ''
) STRICT, WITHOUT ROWID;

CREATE INDEX asset_image_id ON asset (image_id);

-- AssetTag: free tags; one row per tag of an asset, removed with the asset.
CREATE TABLE asset_tag (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  asset_id TEXT NOT NULL REFERENCES asset (id) ON DELETE CASCADE,
  tag TEXT NOT NULL CHECK (tag <> ''),
  UNIQUE (asset_id, tag)
) STRICT, WITHOUT ROWID;

CREATE INDEX asset_tag_tag ON asset_tag (tag);

CREATE TABLE campaign (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  name TEXT NOT NULL CHECK (name <> ''),
  description TEXT NOT NULL DEFAULT '',
  rules_version TEXT NOT NULL DEFAULT '5e-2014'
) STRICT, WITHOUT ROWID;

-- Session: ordered within its campaign, deleted with it (specs/03-domain-model.md §2, §7).
-- `date` is an optional calendar date, YYYY-MM-DD.
CREATE TABLE session (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  campaign_id TEXT NOT NULL REFERENCES campaign (id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (title <> ''),
  "order" INTEGER NOT NULL CHECK ("order" >= 0),
  date TEXT CHECK (date IS NULL OR coalesce(date(date) = date, 0)),
  UNIQUE (campaign_id, "order")
) STRICT, WITHOUT ROWID;

-- Scene: ordered within its session, deleted with it; the map is optional
-- (specs/03-domain-model.md §2, §6). The grid is stored in original-image
-- dimensions (specs/06-grid-and-measurement.md §2); `grid_size` is NULL until a
-- square size is calibrated, which a scene without a map never has. The extent
-- defaults to 30 × 20 and feet per square to 5 (specs/06-grid-and-measurement.md §5).
CREATE TABLE scene (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  session_id TEXT NOT NULL REFERENCES session (id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (name <> ''),
  "order" INTEGER NOT NULL CHECK ("order" >= 0),
  map_image_id TEXT REFERENCES image (id) ON DELETE RESTRICT,
  grid_type TEXT NOT NULL DEFAULT 'square',
  grid_size REAL CHECK (grid_size IS NULL OR (grid_size > 0 AND grid_size < 9e999)),
  grid_offset_x REAL NOT NULL DEFAULT 0 CHECK (abs(grid_offset_x) < 9e999),
  grid_offset_y REAL NOT NULL DEFAULT 0 CHECK (abs(grid_offset_y) < 9e999),
  grid_visible INTEGER NOT NULL DEFAULT 1 CHECK (grid_visible IN (0, 1)),
  grid_feet_per_square REAL NOT NULL DEFAULT 5 CHECK (grid_feet_per_square > 0 AND grid_feet_per_square < 9e999),
  grid_columns INTEGER NOT NULL DEFAULT 30 CHECK (grid_columns > 0),
  grid_rows INTEGER NOT NULL DEFAULT 20 CHECK (grid_rows > 0),
  -- Without a map there are no pixels to calibrate against.
  CHECK (map_image_id IS NOT NULL OR grid_size IS NULL),
  UNIQUE (session_id, "order")
) STRICT, WITHOUT ROWID;

CREATE INDEX scene_map_image_id ON scene (map_image_id);

-- Token: an instance of an asset on a scene, positioned in decimal grid units
-- (specs/03-domain-model.md §2, §4). Deleted with its scene; its asset cannot be
-- deleted while it exists (specs/03-domain-model.md §7).
CREATE TABLE token (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  scene_id TEXT NOT NULL REFERENCES scene (id) ON DELETE CASCADE,
  asset_id TEXT NOT NULL REFERENCES asset (id) ON DELETE RESTRICT,
  label TEXT NOT NULL CHECK (label <> ''),
  x REAL NOT NULL CHECK (abs(x) < 9e999),
  y REAL NOT NULL CHECK (abs(y) < 9e999),
  hidden INTEGER NOT NULL CHECK (hidden IN (0, 1)),
  z_order INTEGER NOT NULL,
  character_id TEXT
) STRICT, WITHOUT ROWID;

CREATE INDEX token_scene_id ON token (scene_id);
CREATE INDEX token_asset_id ON token (asset_id);

-- Settings: one row per server (one game per server). Deleting the live scene,
-- or a session or campaign holding it, clears `live_scene_id`
-- (specs/03-domain-model.md §7). `pin_hash` is NULL until the PIN is set (SRV-02).
CREATE TABLE settings (
  id TEXT NOT NULL PRIMARY KEY CHECK (id GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'),
  live_scene_id TEXT REFERENCES scene (id) ON DELETE SET NULL,
  ruler_rule TEXT NOT NULL DEFAULT 'phb' CHECK (ruler_rule IN ('phb', 'dmg')),
  upload_limit_bytes INTEGER NOT NULL DEFAULT 52428800 CHECK (upload_limit_bytes > 0),
  display_variant_size INTEGER NOT NULL DEFAULT 4096 CHECK (display_variant_size > 0),
  pin_hash TEXT CHECK (pin_hash IS NULL OR pin_hash <> '')
) STRICT, WITHOUT ROWID;

CREATE INDEX settings_live_scene_id ON settings (live_scene_id);

-- The one settings row, under a version 4 UUID generated here, by the server.
INSERT INTO settings (id) VALUES (
  lower(
    hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-'
      || substr('89ab', 1 + (random() & 3), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))
  )
);

CREATE TRIGGER settings_single_row BEFORE INSERT ON settings
BEGIN
  SELECT RAISE(ABORT, 'settings holds exactly one row');
END;

CREATE TRIGGER settings_kept BEFORE DELETE ON settings
BEGIN
  SELECT RAISE(ABORT, 'settings holds exactly one row');
END;

CREATE TRIGGER settings_id_fixed BEFORE UPDATE OF id ON settings
WHEN NEW.id IS NOT OLD.id
BEGIN
  SELECT RAISE(ABORT, 'settings.id never changes');
END;

-- Prepared for later phases (specs/03-domain-model.md §8).
CREATE TRIGGER token_character_id_insert BEFORE INSERT ON token
WHEN NEW.character_id IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'token.character_id stays empty in the MVP');
END;

CREATE TRIGGER token_character_id_update BEFORE UPDATE OF character_id ON token
WHEN NEW.character_id IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'token.character_id stays empty in the MVP');
END;

CREATE TRIGGER scene_grid_type_insert BEFORE INSERT ON scene
WHEN NEW.grid_type IS NOT 'square'
BEGIN
  SELECT RAISE(ABORT, 'scene.grid_type accepts only square in the MVP');
END;

CREATE TRIGGER scene_grid_type_update BEFORE UPDATE OF grid_type ON scene
WHEN NEW.grid_type IS NOT 'square'
BEGIN
  SELECT RAISE(ABORT, 'scene.grid_type accepts only square in the MVP');
END;

CREATE TRIGGER image_grid_preset_type_insert BEFORE INSERT ON image
WHEN NEW.grid_preset_type IS NOT NULL AND NEW.grid_preset_type IS NOT 'square'
BEGIN
  SELECT RAISE(ABORT, 'image.grid_preset_type accepts only square in the MVP');
END;

CREATE TRIGGER image_grid_preset_type_update BEFORE UPDATE OF grid_preset_type ON image
WHEN NEW.grid_preset_type IS NOT NULL AND NEW.grid_preset_type IS NOT 'square'
BEGIN
  SELECT RAISE(ABORT, 'image.grid_preset_type accepts only square in the MVP');
END;

CREATE TRIGGER campaign_rules_version_insert BEFORE INSERT ON campaign
WHEN NEW.rules_version IS NOT '5e-2014'
BEGIN
  SELECT RAISE(ABORT, 'campaign.rules_version is 5e-2014 in the MVP');
END;

CREATE TRIGGER campaign_rules_version_update BEFORE UPDATE OF rules_version ON campaign
WHEN NEW.rules_version IS NOT '5e-2014'
BEGIN
  SELECT RAISE(ABORT, 'campaign.rules_version is 5e-2014 in the MVP');
END;
