// Contract types and constants shared by server and client (specs/02-architecture.md §1).
export { VIEW_PATHS, viewForPath, type View } from './views.js';
export {
  ERROR_CODES,
  ErrorDetailSchema,
  ErrorEnvelopeSchema,
  errorEnvelope,
  type ErrorCode,
  type ErrorDetail,
  type ErrorEnvelope,
} from './errors.js';
export {
  COMMAND_TYPES,
  CommandEnvelopeSchema,
  EVENT_TYPES,
  EventEnvelopeSchema,
  SOCKET_CHANNELS,
  type CommandAck,
  type CommandEnvelope,
  type CommandType,
  type EventEnvelope,
  type EventType,
} from './live.js';
export {
  ASSET_CATEGORIES,
  AssetSchema,
  AssetTagSchema,
  CampaignSchema,
  DEFAULT_FEET_PER_SQUARE,
  DEFAULT_GRID_EXTENT,
  DEFAULT_SETTINGS,
  GRID_TYPES,
  GridPresetSchema,
  GridSchema,
  IMAGE_MIME_TYPES,
  ImageSchema,
  ImageVariantSchema,
  ImageVariantsSchema,
  RULER_RULES,
  RULES_VERSION,
  SceneSchema,
  SessionSchema,
  SettingsSchema,
  Sha256Schema,
  TOKEN_SIZES,
  TokenSchema,
  UuidSchema,
  type Asset,
  type AssetCategory,
  type AssetTag,
  type Campaign,
  type Grid,
  type GridPreset,
  type Image,
  type ImageMime,
  type ImageVariants,
  type RulerRule,
  type Scene,
  type Session,
  type Settings,
  type Token,
  type TokenSize,
} from './entities.js';
export {
  API_PATHS,
  AuthStateSchema,
  PIN_PATTERN,
  PUBLIC_API_ROUTES,
  PinBodySchema,
  PinChangeBodySchema,
  PinSchema,
  SetupStateSchema,
  type AuthState,
  type PinBody,
  type PinChangeBody,
  type SetupState,
} from './auth.js';
export {
  API_STRUCTURE_PATHS,
  CALENDAR_DATE_PATTERN,
  CampaignCreateBodySchema,
  CampaignUpdateBodySchema,
  DeleteBodySchema,
  DeletionSummarySchema,
  IdParamsSchema,
  OrderBodySchema,
  SceneCreateBodySchema,
  SceneDuplicateBodySchema,
  SceneUpdateBodySchema,
  SessionCreateBodySchema,
  SessionUpdateBodySchema,
  isCalendarDate,
  type CampaignCreateBody,
  type CampaignUpdateBody,
  type DeleteBody,
  type DeletionSummary,
  type IdParams,
  type OrderBody,
  type SceneCreateBody,
  type SceneDuplicateBody,
  type SceneUpdateBody,
  type SessionCreateBody,
  type SessionUpdateBody,
} from './campaigns.js';
export {
  API_IMAGE_PATHS,
  IMAGE_FILE_PATH,
  IMAGE_VARIANTS,
  ImageIdParamsSchema,
  THUMBNAIL_SIZE,
  imageFileUrl,
  type ImageIdParams,
  type ImageVariant,
} from './images.js';
