// Contract types and constants shared by server and client (specs/02-architecture.md §1).
export { VIEW_PATHS, viewForPath, type View } from './views.js';
export {
  ERROR_CODES,
  ErrorDetailSchema,
  ErrorEnvelopeSchema,
  errorEnvelope,
  type ErrorCode,
  type ErrorDetail,
  type ErrorEnvelope,
} from './errors.js';
export {
  COMMAND_TYPES,
  CommandEnvelopeSchema,
  EVENT_TYPES,
  DmLiveSceneSchema,
  DmSnapshotSchema,
  EventEnvelopeSchema,
  PlayerLiveSceneSchema,
  PlayerMapSchema,
  PlayerSnapshotSchema,
  PlayerTokenSchema,
  PLAYER_VIEW_AUTH,
  ROOMS,
  SceneSnapshotSchema,
  SOCKET_CHANNELS,
  SOCKET_PATH,
  HEARTBEAT_INTERVAL_MS,
  SOCKET_REFUSALS,
  HEARTBEAT_TIMEOUT_MS,
  type CommandAck,
  type CommandEnvelope,
  type CommandType,
  type DmLiveScene,
  type DmSnapshot,
  type EventEnvelope,
  type EventType,
  type PlayerLiveScene,
  type PlayerMap,
  type PlayerSnapshot,
  type PlayerToken,
  type Room,
  type SceneSnapshot,
  type SnapshotAck,
  type SnapshotEvent,
  CAMERA_BOUNDS,
  CameraSetPlayerPayloadSchema,
  DmCameraPayloadSchema,
  FIT_CAMERA,
  PlayerCameraPayloadSchema,
  PlayerCameraSchema,
  ScreenSchema,
  type CameraSetPlayerPayload,
  type DmCameraPayload,
  type PlayerCamera,
  type PlayerCameraPayload,
  type Screen,
  type ViewportAck,
  DmTokenEventPayloadSchema,
  LIVE_COMMAND_PAYLOAD_SCHEMAS,
  PlayerTokenAddedPayloadSchema,
  PlayerTokenUpdatedPayloadSchema,
  SceneActivatePayloadSchema,
  SceneClearedPayloadSchema,
  SceneDeactivatePayloadSchema,
  UndoPayloadSchema,
  RedoPayloadSchema,
  UndoStateSchema,
  HistoryChangedPayloadSchema,
  TokenAddPayloadSchema,
  TokenDeletePayloadSchema,
  TokenMovePayloadSchema,
  TokenRemovedPayloadSchema,
  TokenSetVisibilityPayloadSchema,
  TokenSetMarkersPayloadSchema,
  TokenSetStatsPayloadSchema,
  TokenApplyHpPayloadSchema,
  TokenBatchPayloadSchema,
  BatchedCommandSchema,
  BATCH_COMMAND_TYPES,
  MAX_BATCH_COMMANDS,
  type DmEvent,
  type DmTokenEventPayload,
  type PlayerEvent,
  type PlayerTokenAddedPayload,
  type PlayerTokenUpdatedPayload,
  type SceneActivatePayload,
  type SceneClearedPayload,
  type SceneDeactivatePayload,
  type UndoPayload,
  type RedoPayload,
  type UndoState,
  type HistoryChangedPayload,
  type TokenAddPayload,
  type TokenDeletePayload,
  type TokenMovePayload,
  type TokenRemovedPayload,
  type TokenSetVisibilityPayload,
  type TokenSetMarkersPayload,
  type TokenSetStatsPayload,
  type TokenApplyHpPayload,
  type TokenBatchPayload,
  type BatchedCommand,
  type BatchCommandType,
  MeasurementSchema,
  RulerClearPayloadSchema,
  RulerClearedPayloadSchema,
  RulerShownPayloadSchema,
  RulerSquareSchema,
  RulerUpdatePayloadSchema,
  type Measurement,
  type RulerClearPayload,
  type RulerClearedPayload,
  type RulerShownPayload,
  type RulerUpdatePayload,
  PingPayloadSchema,
  PingShownPayloadSchema,
  type PingPayload,
  type PingShownPayload,
  FogPaintPayloadSchema,
  FogFillPayloadSchema,
  FogUpdatedPayloadSchema,
  type FogPaintPayload,
  type FogFillPayload,
  type FogUpdatedPayload,
  EncounterScenePayloadSchema,
  EncounterReorderPayloadSchema,
  EncounterSetInitiativePayloadSchema,
  EncounterAddEntryPayloadSchema,
  EncounterRemoveEntryPayloadSchema,
  DmEncounterPayloadSchema,
  PlayerEncounterPayloadSchema,
  type EncounterScenePayload,
  type EncounterReorderPayload,
  type EncounterSetInitiativePayload,
  type EncounterAddEntryPayload,
  type EncounterRemoveEntryPayload,
  type DmEncounterPayload,
  type PlayerEncounterPayload,
} from './live.js';
export {
  MonsterEntrySchema,
  EncounterEntrySchema,
  EncounterSchema,
  INITIATIVE_BOUNDS,
  InitiativeSchema,
  MAX_ENCOUNTER_ENTRIES,
  PcEntrySchema,
  PlayerEncounterEntrySchema,
  PlayerEncounterSchema,
  canEnter,
  changeOf,
  enemiesCanAct,
  entryKindOf,
  firstTurn,
  insertionIndex,
  noEnemiesLeft,
  followTurn,
  notingEnemies,
  withoutEntry,
  isEncounter,
  isPlayerEncounter,
  missingTokens,
  nextIndex,
  playerEncounter,
  samePlayerEncounter,
  sortByInitiative,
  startTokens,
  stepTurn,
  takesTurn,
  turnView,
  type MonsterEntry,
  type Encounter,
  type EncounterChange,
  type EncounterDecision,
  type EncounterRefusal,
  type EncounterScene,
  type EncounterEntry,
  type EncounterToken,
  type PcEntry,
  type PlayerEncounter,
  type PlayerEncounterEntry,
  type TurnView,
} from './encounter.js';
export {
  API_FOG_PATHS,
  EMPTY_FOG,
  FOG_BRUSH_RADIUS,
  FOG_CELLS_PER_SQUARE,
  FOG_MAX_RUNS,
  FOG_STROKE_MAX_POINTS,
  FOG_STROKE_MAX_WORK,
  FogMaskSchema,
  FogRowSchema,
  FogStrokeSchema,
  FogWriteBodySchema,
  applyStroke,
  fillFog,
  fogExtent,
  fogRuns,
  inFog,
  isFogMask,
  sameFog,
  seenByPlayers,
  strokeCells,
  strokeWork,
  tokenCentre,
  type FogExtent,
  type FogMask,
  type FogRow,
  type FogStroke,
  type FogWriteBody,
} from './fog.js';
export {
  CONDITIONS,
  CONDITION_IDS,
  EXHAUSTION,
  EXHAUSTION_LEVELS,
  MAX_BADGES,
  MAX_MARKERS,
  MarkerSchema,
  MarkersSchema,
  badgeOrder,
  badgesOf,
  conditionOf,
  hasMarker,
  markerLevel,
  normaliseMarkers,
  repeatsCondition,
  sameMarkers,
  type Condition,
  type ConditionIcon,
  type TokenMarker,
} from './conditions.js';
export {
  AC_BOUNDS,
  AcSchema,
  HP_BOUNDS,
  HpDeltaSchema,
  HpMaxSchema,
  HpSchema,
  STAT_FIELDS,
  applyHp,
  compactHp,
  downMarker,
  hpChanged,
  isBloodied,
  markersForHp,
  parseHpEntry,
  sameStats,
  statsFromAsset,
  statsOf,
  withStats,
  type HpDelta,
  type HpEntry,
  type TokenStats,
} from './hp.js';
export { isMeasurement, rulerFeet, rulerSquares, type RulerSquare } from './ruler.js';
export {
  API_NOTES_PATHS,
  NOTES_MAX_LENGTH,
  NotesBodySchema,
  NotesSchema,
  NotesUpdatedPayloadSchema,
  hasNotes,
  notesLength,
  notesPreview,
  type NotesBody,
  type NotesUpdatedPayload,
} from './notes.js';
export {
  API_MAP_NOTE_PATHS,
  MapNoteCreateBodySchema,
  MapNoteDeleteQuerySchema,
  MapNoteSchema,
  MapNoteUpdateBodySchema,
  MapNotesUpdatedPayloadSchema,
  type MapNote,
  type MapNoteCreateBody,
  type MapNoteDeleteQuery,
  type MapNoteUpdateBody,
  type MapNotesUpdatedPayload,
} from './mapNotes.js';
export {
  ASSET_CATEGORIES,
  AssetSchema,
  AssetTagSchema,
  CampaignSchema,
  DEFAULT_FEET_PER_SQUARE,
  DEFAULT_GRID_EXTENT,
  DEFAULT_SETTINGS,
  IPV4_PATTERN,
  Ipv4Schema,
  GRID_TYPES,
  GridPresetSchema,
  GridSchema,
  IMAGE_MIME_TYPES,
  ImageSchema,
  ImageVariantSchema,
  ImageVariantsSchema,
  RULER_RULES,
  RULES_VERSION,
  SceneSchema,
  SessionSchema,
  SettingsSchema,
  Sha256Schema,
  TOKEN_SIZES,
  TokenSchema,
  UuidSchema,
  type Asset,
  type AssetCategory,
  type AssetTag,
  type Campaign,
  type Grid,
  type GridPreset,
  type Image,
  type ImageMime,
  type ImageVariants,
  type RulerRule,
  type Scene,
  type Session,
  type Settings,
  type Token,
  type TokenSize,
} from './entities.js';
export {
  API_PATHS,
  AuthStateSchema,
  PIN_PATTERN,
  PUBLIC_API_ROUTES,
  PinBodySchema,
  PinChangeBodySchema,
  PinSchema,
  SetupStateSchema,
  type AuthState,
  type PinBody,
  type PinChangeBody,
  type SetupState,
} from './auth.js';
export {
  API_ARCHIVE_PATHS,
  ARCHIVE_DATA_FILES,
  ARCHIVE_DATA_SCHEMAS,
  ARCHIVE_ENTRY_PATTERN,
  ARCHIVE_FORMAT_VERSION,
  ARCHIVE_KINDS,
  ArchiveAssetSchema,
  ArchiveCountsSchema,
  ArchiveImageSchema,
  ArchiveManifestSchema,
  ArchiveSceneSchema,
  ArchiveTokenSchema,
  ArchiveMapNoteSchema,
  ADDED_IN_FORMAT_2,
  AssetExportQuerySchema,
  IMAGE_EXTENSIONS,
  IMPORT_LIMIT_BOUNDS,
  IMPORT_STAGES,
  ImportProgressSchema,
  ImportSummarySchema,
  MAX_ARCHIVE_ENTRIES,
  MAX_DATA_FILE_BYTES,
  MAX_MANIFEST_BYTES,
  TokenNumbersSchema,
  calendarDate,
  exportCampaignPath,
  exportFileName,
  freeCampaignName,
  migrateFormat,
  safeFileName,
  type ArchiveAsset,
  type ArchiveCounts,
  type ArchiveData,
  type ArchiveDataName,
  type ArchiveImage,
  type ArchiveKind,
  type ArchiveManifest,
  type ArchiveScene,
  type ArchiveToken,
  type ArchiveMapNote,
  type AssetExportQuery,
  type ImportProgress,
  type ImportStage,
  type ImportSummary,
} from './archive.js';
export { DISPLAY_SIZE_BOUNDS, SettingsUpdateSchema, UPLOAD_LIMIT_BOUNDS, type SettingsUpdate } from './settings.js';
export {
  API_STRUCTURE_PATHS,
  CALENDAR_DATE_PATTERN,
  CALIBRATION_FIELDS,
  FEET_PER_SQUARE_BOUNDS,
  MAX_GRID_LINES_PER_AXIS,
  CampaignCreateBodySchema,
  CampaignUpdateBodySchema,
  DeleteBodySchema,
  DeletionSummarySchema,
  IdParamsSchema,
  OrderBodySchema,
  SceneCreateBodySchema,
  SceneDuplicateBodySchema,
  SceneGridUpdateSchema,
  SceneUpdateBodySchema,
  SceneSummarySchema,
  SessionCreateBodySchema,
  SessionUpdateBodySchema,
  isCalendarDate,
  type CampaignCreateBody,
  type CampaignUpdateBody,
  type DeleteBody,
  type DeletionSummary,
  type IdParams,
  type OrderBody,
  type SceneCreateBody,
  type SceneDuplicateBody,
  type SceneGridUpdate,
  type SceneUpdateBody,
  type SceneSummary,
  type SessionCreateBody,
  type SessionUpdateBody,
} from './campaigns.js';
export {
  API_IMAGE_PATHS,
  IMAGE_FILE_PATH,
  IMAGE_VARIANTS,
  ImageIdParamsSchema,
  THUMBNAIL_SIZE,
  imageFileUrl,
  type ImageIdParams,
  type ImageVariant,
} from './images.js';
export {
  API_ASSET_PATHS,
  AssetCreateBodySchema,
  AssetListQuerySchema,
  AssetUpdateBodySchema,
  AssetUsageSchema,
  AssetUsagesSchema,
  LibraryAssetSchema,
  TOKEN_FOOTPRINT,
  normalizeTag,
  type AssetCreateBody,
  type AssetListQuery,
  type AssetUpdateBody,
  type AssetUsage,
  type LibraryAsset,
} from './assets.js';
export {
  API_TOKEN_PATHS,
  SceneTokenSchema,
  TOKEN_STACK,
  TokenCreateBodySchema,
  TokenChangeSchema,
  TokenUpdateBodySchema,
  type SceneToken,
  type TokenCreateBody,
  type TokenChange,
  type TokenStack,
  type TokenUpdateBody,
} from './tokens.js';
export { nextLabel, numberingPeers, numberOf, type LabelledToken, type Numbering } from './numbering.js';
export {
  API_CONNECT_PATH,
  API_SCREENS_PATH,
  ScreenCountSchema,
  type ScreenCount,
  ConnectAddressSchema,
  ConnectInfoSchema,
  QrCodeSchema,
  type ConnectAddress,
  type ConnectInfo,
  type QrCode,
} from './connect.js';
