// Contract types and constants shared by server and client (specs/02-architecture.md §1).
export { VIEW_PATHS, viewForPath, type View } from './views.js';
export {
  ERROR_CODES,
  ErrorDetailSchema,
  ErrorEnvelopeSchema,
  errorEnvelope,
  type ErrorCode,
  type ErrorDetail,
  type ErrorEnvelope,
} from './errors.js';
export {
  COMMAND_TYPES,
  CommandEnvelopeSchema,
  EVENT_TYPES,
  DmLiveSceneSchema,
  DmSnapshotSchema,
  EventEnvelopeSchema,
  PlayerLiveSceneSchema,
  PlayerMapSchema,
  PlayerSnapshotSchema,
  PlayerTokenSchema,
  PLAYER_VIEW_AUTH,
  ROOMS,
  SceneSnapshotSchema,
  SOCKET_CHANNELS,
  SOCKET_PATH,
  type CommandAck,
  type CommandEnvelope,
  type CommandType,
  type DmLiveScene,
  type DmSnapshot,
  type EventEnvelope,
  type EventType,
  type PlayerLiveScene,
  type PlayerMap,
  type PlayerSnapshot,
  type PlayerToken,
  type Room,
  type SceneSnapshot,
  type SnapshotAck,
  type SnapshotEvent,
  DmTokenEventPayloadSchema,
  LIVE_COMMAND_PAYLOAD_SCHEMAS,
  PlayerTokenAddedPayloadSchema,
  PlayerTokenUpdatedPayloadSchema,
  SceneActivatePayloadSchema,
  SceneClearedPayloadSchema,
  SceneDeactivatePayloadSchema,
  TokenAddPayloadSchema,
  TokenDeletePayloadSchema,
  TokenMovePayloadSchema,
  TokenRemovedPayloadSchema,
  TokenSetVisibilityPayloadSchema,
  type DmEvent,
  type DmTokenEventPayload,
  type PlayerEvent,
  type PlayerTokenAddedPayload,
  type PlayerTokenUpdatedPayload,
  type SceneActivatePayload,
  type SceneClearedPayload,
  type SceneDeactivatePayload,
  type TokenAddPayload,
  type TokenDeletePayload,
  type TokenMovePayload,
  type TokenRemovedPayload,
  type TokenSetVisibilityPayload,
} from './live.js';
export {
  ASSET_CATEGORIES,
  AssetSchema,
  AssetTagSchema,
  CampaignSchema,
  DEFAULT_FEET_PER_SQUARE,
  DEFAULT_GRID_EXTENT,
  DEFAULT_SETTINGS,
  GRID_TYPES,
  GridPresetSchema,
  GridSchema,
  IMAGE_MIME_TYPES,
  ImageSchema,
  ImageVariantSchema,
  ImageVariantsSchema,
  RULER_RULES,
  RULES_VERSION,
  SceneSchema,
  SessionSchema,
  SettingsSchema,
  Sha256Schema,
  TOKEN_SIZES,
  TokenSchema,
  UuidSchema,
  type Asset,
  type AssetCategory,
  type AssetTag,
  type Campaign,
  type Grid,
  type GridPreset,
  type Image,
  type ImageMime,
  type ImageVariants,
  type RulerRule,
  type Scene,
  type Session,
  type Settings,
  type Token,
  type TokenSize,
} from './entities.js';
export {
  API_PATHS,
  AuthStateSchema,
  PIN_PATTERN,
  PUBLIC_API_ROUTES,
  PinBodySchema,
  PinChangeBodySchema,
  PinSchema,
  SetupStateSchema,
  type AuthState,
  type PinBody,
  type PinChangeBody,
  type SetupState,
} from './auth.js';
export {
  API_STRUCTURE_PATHS,
  CALENDAR_DATE_PATTERN,
  CALIBRATION_FIELDS,
  MAX_GRID_LINES_PER_AXIS,
  CampaignCreateBodySchema,
  CampaignUpdateBodySchema,
  DeleteBodySchema,
  DeletionSummarySchema,
  IdParamsSchema,
  OrderBodySchema,
  SceneCreateBodySchema,
  SceneDuplicateBodySchema,
  SceneGridUpdateSchema,
  SceneUpdateBodySchema,
  SessionCreateBodySchema,
  SessionUpdateBodySchema,
  isCalendarDate,
  type CampaignCreateBody,
  type CampaignUpdateBody,
  type DeleteBody,
  type DeletionSummary,
  type IdParams,
  type OrderBody,
  type SceneCreateBody,
  type SceneDuplicateBody,
  type SceneGridUpdate,
  type SceneUpdateBody,
  type SessionCreateBody,
  type SessionUpdateBody,
} from './campaigns.js';
export {
  API_IMAGE_PATHS,
  IMAGE_FILE_PATH,
  IMAGE_VARIANTS,
  ImageIdParamsSchema,
  THUMBNAIL_SIZE,
  imageFileUrl,
  type ImageIdParams,
  type ImageVariant,
} from './images.js';
export {
  API_ASSET_PATHS,
  AssetCreateBodySchema,
  AssetListQuerySchema,
  AssetUpdateBodySchema,
  AssetUsageSchema,
  AssetUsagesSchema,
  LibraryAssetSchema,
  TOKEN_FOOTPRINT,
  normalizeTag,
  type AssetCreateBody,
  type AssetListQuery,
  type AssetUpdateBody,
  type AssetUsage,
  type LibraryAsset,
} from './assets.js';
export {
  API_TOKEN_PATHS,
  SceneTokenSchema,
  TOKEN_STACK,
  TokenCreateBodySchema,
  TokenChangeSchema,
  TokenUpdateBodySchema,
  type SceneToken,
  type TokenCreateBody,
  type TokenChange,
  type TokenStack,
  type TokenUpdateBody,
} from './tokens.js';
export { nextLabel, numberingPeers, numberOf, type LabelledToken, type Numbering } from './numbering.js';
export {
  API_CONNECT_PATH,
  ConnectAddressSchema,
  ConnectInfoSchema,
  QrCodeSchema,
  type ConnectAddress,
  type ConnectInfo,
  type QrCode,
} from './connect.js';
